//! The regex stage against the spoken-reference corpus (M2 deliverable 1).
//!
//! `tests/fixtures/spoken_references.tsv` is generated by
//! `scripts/make-reference-corpus.py` and holds every surface form the stage
//! claims to handle, seeded from lines Nova-3 actually produced. Each line is
//! `input<TAB>expected`, where expected is a USFM passage ID or `-`.
//!
//! Two thresholds, deliberately asymmetric:
//!
//! - **References: 95% or better** — the M2 Definition of Done figure. A miss
//!   here is recoverable: the vector and paraphrase stages get another look.
//! - **Negatives: zero false hits.** A false hit puts a verse in staging that
//!   nobody said. Even marked provisional, an operator who watches candidates
//!   appear and retract stops trusting the panel (PRD §18.1), and that is not
//!   recoverable by a later stage.
//!
//! Every failing line is printed, so the number is never the only thing known.

use std::fs;

use sermonai_lib::detection::regex::scan;

#[derive(Debug)]
struct Case {
    input: String,
    expected: Option<String>,
}

fn corpus() -> Vec<Case> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/spoken_references.tsv"
    );
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("could not read the corpus at {path}: {e}"));

    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|line| {
            let (input, expected) = line
                .split_once('\t')
                .unwrap_or_else(|| panic!("corpus line has no tab: {line:?}"));
            Case {
                input: input.to_string(),
                expected: (expected != "-").then(|| expected.to_string()),
            }
        })
        .collect()
}

#[test]
fn the_corpus_is_as_large_as_the_milestone_asks() {
    let cases = corpus();
    let references = cases.iter().filter(|c| c.expected.is_some()).count();
    assert!(
        cases.len() >= 300,
        "the deliverable asks for 300 variants; the corpus has {}",
        cases.len()
    );
    assert!(
        references >= 250,
        "only {references} of the cases are references"
    );
    // Enough negatives to mean something. A corpus of references alone would
    // let a scanner that matches everything score 100%.
    assert!(cases.len() - references >= 25);
}

#[test]
fn at_least_95_percent_of_references_are_caught() {
    let cases = corpus();
    let mut total = 0usize;
    let mut caught = 0usize;
    let mut misses = Vec::new();

    for case in cases.iter().filter(|c| c.expected.is_some()) {
        total += 1;
        let expected = case.expected.as_deref().unwrap();
        let hits = scan(&case.input);
        let found = hits.iter().any(|h| h.reference.passage_id() == expected);
        if found {
            caught += 1;
        } else {
            let got: Vec<String> = hits.iter().map(|h| h.reference.passage_id()).collect();
            misses.push(format!(
                "  {:<70} wanted {expected:<14} got {got:?}",
                case.input
            ));
        }
    }

    let rate = caught as f64 / total as f64;
    eprintln!(
        "regex stage: {caught}/{total} references caught ({:.1}%)",
        rate * 100.0
    );
    if !misses.is_empty() {
        eprintln!("missed:\n{}", misses.join("\n"));
    }
    assert!(
        rate >= 0.95,
        "{caught} of {total} caught = {:.1}%, below the 95% the DoD asks for",
        rate * 100.0
    );
}

#[test]
fn no_negative_produces_a_reference() {
    let cases = corpus();
    let mut false_hits = Vec::new();

    for case in cases.iter().filter(|c| c.expected.is_none()) {
        let hits = scan(&case.input);
        if !hits.is_empty() {
            let got: Vec<String> = hits
                .iter()
                .map(|h| format!("{} ({:?})", h.reference.passage_id(), h.form))
                .collect();
            false_hits.push(format!("  {:<50} produced {got:?}", case.input));
        }
    }

    assert!(
        false_hits.is_empty(),
        "{} sentence(s) with no reference in them produced one:\n{}",
        false_hits.len(),
        false_hits.join("\n")
    );
}

#[test]
fn the_verbatim_transcript_lines_all_pass() {
    // The seven lines that came back from Nova-3 verbatim are the ones the
    // rest of the corpus imitates. If a generated variant fails that is a gap
    // in the scanner; if one of these fails the scanner does not match what
    // the transcript actually says, which is the only thing that matters.
    let cases = corpus();
    let verbatim = [
        (
            "this morning to the book of Jeremiah. Chapter 29. Verse 11,",
            Some("JER.29.11"),
        ),
        (
            "He said in Romans eight twenty eight that all",
            Some("ROM.8.28"),
        ),
        (
            "Turn with me if you will to first Thessalonians chapter five.",
            Some("1TH.5.1"),
        ),
        ("Look at what John writes in his first epistle.", None),
    ];
    for (input, expected) in verbatim {
        assert!(
            cases.iter().any(|c| c.input == input),
            "the corpus no longer contains the measured line {input:?}"
        );
        let hits = scan(input);
        let got: Vec<String> = hits.iter().map(|h| h.reference.passage_id()).collect();
        match expected {
            Some(e) => assert!(
                got.iter().any(|g| g == e),
                "{input:?}: wanted {e}, got {got:?}"
            ),
            None => assert!(got.is_empty(), "{input:?}: must not match, got {got:?}"),
        }
    }
}
